/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;



public class modelo extends javax.swing.JFrame {

    ImageIcon Imagen[] = new ImageIcon[6];
    int contador=1;
    int clic=0;
    Timer timer;
   
    public modelo() {
        initComponents();
        for (int i=1; i<6; i++){
            Imagen[i] = new ImageIcon (getClass().getResource("/visor/imagenes/im"+i+".jpg"));
        }
        contenedor.setIcon(Imagen[1]);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        batras = new javax.swing.JButton();
        bauto = new javax.swing.JButton();
        bsig = new javax.swing.JButton();
        contenedor = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batras.setText("ATRAS");
        batras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batrasActionPerformed(evt);
            }
        });
        getContentPane().add(batras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 100, 30));

        bauto.setText("AUTO");
        bauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bautoActionPerformed(evt);
            }
        });
        getContentPane().add(bauto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 100, 30));

        bsig.setText("SIGUIENTE");
        bsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsigActionPerformed(evt);
            }
        });
        getContentPane().add(bsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 100, 30));

        contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        contenedor.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visor/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 471));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsigActionPerformed
           if(contador == 5){
           contador=0;}
           contador++;
           contenedor.setIcon(Imagen[contador]);      
    }//GEN-LAST:event_bsigActionPerformed

    private void bautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bautoActionPerformed
        /*if(timer !=null){
            timer.stop();
            timer = null;
        }*/
        clic++;
        if(clic %2==0)
        timer.stop();
        else{        
        timer = new Timer(600, new ActionListener() {
          @Override
            public void actionPerformed(ActionEvent e) {
            contenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visor/imagenes/im"+contador+".jpg")));
            contador ++;
            if (contador==6)contador =1;
            }
        });
        timer.start(); 
        }
    }//GEN-LAST:event_bautoActionPerformed

    private void batrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batrasActionPerformed
           if(contador == 1){
           contador=6;}
           contador--;
           contenedor.setIcon(Imagen[contador]);
    }//GEN-LAST:event_batrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batras;
    private javax.swing.JButton bauto;
    private javax.swing.JButton bsig;
    private javax.swing.JLabel contenedor;
    private javax.swing.JLabel fondo;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
