package formulario;

import javax.swing.JOptionPane;

public class ObjetosDelFormulario extends javax.swing.JFrame {

   
    public ObjetosDelFormulario() {
        initComponents();
        this.setLocationRelativeTo(null); //para que arranque centrado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGSEXO = new javax.swing.ButtonGroup();
        jPIDIOMAS = new javax.swing.JPanel();
        jCBIngles = new javax.swing.JCheckBox();
        jCBPortugues = new javax.swing.JCheckBox();
        jCBFrances = new javax.swing.JCheckBox();
        jCBOtros = new javax.swing.JCheckBox();
        jLTITULO = new javax.swing.JLabel();
        jPDATOS = new javax.swing.JPanel();
        jLApellidoPaterno = new javax.swing.JLabel();
        jLApellidoMaterno = new javax.swing.JLabel();
        jLNombre1 = new javax.swing.JLabel();
        jLNombre2 = new javax.swing.JLabel();
        jTexRespuestaApellPaterno = new javax.swing.JTextField();
        jTexRespuestaApellMaterno = new javax.swing.JTextField();
        jTexRespuestaNombre1 = new javax.swing.JTextField();
        jTexRespuestaNombre2 = new javax.swing.JTextField();
        jLDNI = new javax.swing.JLabel();
        jTexRespuestaDNI = new javax.swing.JTextField();
        jLEdad = new javax.swing.JLabel();
        jLFechaNac = new javax.swing.JLabel();
        jCBDIA = new javax.swing.JComboBox<>();
        jCBMES = new javax.swing.JComboBox<>();
        jCBANIO = new javax.swing.JComboBox<>();
        jTexRespuestaEdad = new javax.swing.JTextField();
        jBENVIAR = new javax.swing.JButton();
        jBCANCELAR = new javax.swing.JButton();
        jPSEXO = new javax.swing.JPanel();
        jRBFemenino = new javax.swing.JRadioButton();
        jRBMasculino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPIDIOMAS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IDIOMAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jCBIngles.setText("Inglés");
        jCBIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBInglesActionPerformed(evt);
            }
        });

        jCBPortugues.setText("Portugués");

        jCBFrances.setText("Francés");

        jCBOtros.setText("Otros");

        javax.swing.GroupLayout jPIDIOMASLayout = new javax.swing.GroupLayout(jPIDIOMAS);
        jPIDIOMAS.setLayout(jPIDIOMASLayout);
        jPIDIOMASLayout.setHorizontalGroup(
            jPIDIOMASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIDIOMASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPIDIOMASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBIngles)
                    .addComponent(jCBPortugues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPIDIOMASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBFrances)
                    .addComponent(jCBOtros))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPIDIOMASLayout.setVerticalGroup(
            jPIDIOMASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIDIOMASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPIDIOMASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPIDIOMASLayout.createSequentialGroup()
                        .addComponent(jCBFrances)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBOtros))
                    .addGroup(jPIDIOMASLayout.createSequentialGroup()
                        .addComponent(jCBIngles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBPortugues)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLTITULO.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTITULO.setText("DATOS PERSONALES DEL EMPLEADO");

        jPDATOS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE LOS DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLApellidoPaterno.setText("Apellido Paterno");

        jLApellidoMaterno.setText("Apellido Materno");

        jLNombre1.setText("Nombre 1");

        jLNombre2.setText("Nombre 2");

        jTexRespuestaApellMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexRespuestaApellMaternoActionPerformed(evt);
            }
        });

        jLDNI.setText("DNI");

        jLEdad.setText("Edad");

        jLFechaNac.setText("Fecha de Nacimiento");

        jCBDIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCBMES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jCBANIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

        javax.swing.GroupLayout jPDATOSLayout = new javax.swing.GroupLayout(jPDATOS);
        jPDATOS.setLayout(jPDATOSLayout);
        jPDATOSLayout.setHorizontalGroup(
            jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDATOSLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLNombre1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLApellidoPaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLApellidoMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jLNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTexRespuestaApellPaterno)
                    .addComponent(jTexRespuestaApellMaterno)
                    .addComponent(jTexRespuestaNombre1)
                    .addComponent(jTexRespuestaNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDATOSLayout.createSequentialGroup()
                        .addComponent(jLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jTexRespuestaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDATOSLayout.createSequentialGroup()
                        .addComponent(jLFechaNac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBDIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBMES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDATOSLayout.createSequentialGroup()
                        .addComponent(jLEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jTexRespuestaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPDATOSLayout.setVerticalGroup(
            jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDATOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexRespuestaApellPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexRespuestaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexRespuestaApellMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexRespuestaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexRespuestaNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBANIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexRespuestaNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jBENVIAR.setText("ENVIAR");
        jBENVIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBENVIARMouseClicked(evt);
            }
        });
        jBENVIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBENVIARActionPerformed(evt);
            }
        });

        jBCANCELAR.setText("CANCELAR");
        jBCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCANCELARActionPerformed(evt);
            }
        });

        jPSEXO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INDIQUE EL SEXO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        bGSEXO.add(jRBFemenino);
        jRBFemenino.setText("Femenino");
        jRBFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFemeninoActionPerformed(evt);
            }
        });

        bGSEXO.add(jRBMasculino);
        jRBMasculino.setText("Masculino");
        jRBMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMasculinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSEXOLayout = new javax.swing.GroupLayout(jPSEXO);
        jPSEXO.setLayout(jPSEXOLayout);
        jPSEXOLayout.setHorizontalGroup(
            jPSEXOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSEXOLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPSEXOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBMasculino)
                    .addComponent(jRBFemenino))
                .addGap(17, 17, 17))
        );
        jPSEXOLayout.setVerticalGroup(
            jPSEXOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSEXOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBFemenino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jRBMasculino)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jPIDIOMAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jBENVIAR)
                                .addGap(31, 31, 31)
                                .addComponent(jBCANCELAR)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPIDIOMAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBENVIAR)
                            .addComponent(jBCANCELAR))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBInglesActionPerformed

    private void jBENVIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBENVIARMouseClicked
        String mensaje;
        if (jRBFemenino.isSelected()){
            mensaje= "Usted es de sexo femenino";
        }else if(jRBMasculino.isSelected()){
            mensaje= "Usted es de sexo masculino";
        } else {
            mensaje= "Elija el sexo";

        }
        JOptionPane.showMessageDialog(this, mensaje);        // TODO add your handling code here:
    }//GEN-LAST:event_jBENVIARMouseClicked

    private void jBCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCANCELARActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBCANCELARActionPerformed

    private void jRBFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBFemeninoActionPerformed

    private void jRBMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBMasculinoActionPerformed

    private void jTexRespuestaApellMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexRespuestaApellMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexRespuestaApellMaternoActionPerformed

    private void jBENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBENVIARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBENVIARActionPerformed
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObjetosDelFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObjetosDelFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObjetosDelFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObjetosDelFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObjetosDelFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGSEXO;
    private javax.swing.JButton jBCANCELAR;
    private javax.swing.JButton jBENVIAR;
    private javax.swing.JComboBox<String> jCBANIO;
    private javax.swing.JComboBox<String> jCBDIA;
    private javax.swing.JCheckBox jCBFrances;
    private javax.swing.JCheckBox jCBIngles;
    private javax.swing.JComboBox<String> jCBMES;
    private javax.swing.JCheckBox jCBOtros;
    private javax.swing.JCheckBox jCBPortugues;
    private javax.swing.JLabel jLApellidoMaterno;
    private javax.swing.JLabel jLApellidoPaterno;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLNombre2;
    private javax.swing.JLabel jLTITULO;
    private javax.swing.JPanel jPDATOS;
    private javax.swing.JPanel jPIDIOMAS;
    private javax.swing.JPanel jPSEXO;
    private javax.swing.JRadioButton jRBFemenino;
    private javax.swing.JRadioButton jRBMasculino;
    private javax.swing.JTextField jTexRespuestaApellMaterno;
    private javax.swing.JTextField jTexRespuestaApellPaterno;
    private javax.swing.JTextField jTexRespuestaDNI;
    private javax.swing.JTextField jTexRespuestaEdad;
    private javax.swing.JTextField jTexRespuestaNombre1;
    private javax.swing.JTextField jTexRespuestaNombre2;
    // End of variables declaration//GEN-END:variables
                  
}

